# Generated by Django 4.0.5 on 2022-07-12 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='postModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=50)),
                ('kategori', models.CharField(max_length=25)),
                ('konten', models.TextField()),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
        ),
    ]
